### PR TITLE
Fix #10 - Enable update and security mirrors for target system

### LINKED ISSUE #10: Target system could use defined mirror for apt
Currently bootstrap/0002_minimal.sh hard codes the http://deb.debian.org/debian/ for the apt repository of the target system.

Might we have the target system pulling package updates from a different mirror to that used for the initial build, e.g. a special APT server? If so, it could be a config option.

### PR DESCRIPTION
**Pull request by danielhjames**
Also:

Echo the dibby command arguments and mirror to confirm user choices
Offer alternative of sudo when permissions are insufficient

Tested on Debian 9.8 'stretch' build host.

### CODE REVIEW

**Review by obbardc — CHANGES_REQUESTED** [review]
<snip>

**Review by obbardc — CHANGES_REQUESTED** [review]
<snip>

**Review by obbardc — APPROVED** [review]

**Review by obbardc — CHANGES_REQUESTED** [review]
54a8369: we should just print every variable from the input & anything specified in default-config
ca378ba: How about for non-debian sources & sid which may not have these repositories?
e4003d1: it's probably easier to commit small changes like this straight to master without pull requests

**Comment by danielhjames** [comment]
As there are only a limited number of suites with update and security support from Debian, the check added in https://github.com/64studio/dibby/pull/15/commits/5189862638b295611dae07a3cd93b360bc52b134 should prevent these extra repos being added in other cases.

**Comment by obbardc** [comment]
Looks good,

I think I'm more inclined to include APT repo in `default-config` to allow the user to override it. This would then work for future sources like Ubuntu, Debian, Mint.

e.g
```
APT_SOURCES_LIST="
deb http://deb.debian.org/debian sid main
deb-src http://deb.debian.org/debian sid main
"
```


Also, how about using `printenv` to print the configuration after it's been loaded in? Some grepping could be done for our variables. e.g all variables set by our script.

**Comment by danielhjames** [comment]
I've added printing of more of the user variables and tightened up the root password setting. Hopefully it shouldn't be necessary for the user to specify the whole sources.list as the format follows a known pattern, but let's see.

**Pull request merged**
