### PR TITLE
Enable root password strength checking with cracklib

### PR DESCRIPTION
**Pull request by danielhjames**
Update readme and control files for additional dependency

### CODE REVIEW

**Comment by obbardc** [comment]
Can this only throw a warning if the password is not strong enough?

**Comment by danielhjames** [comment]
It warns of low password strength by displaying a score out of 100, where 100 is most secure. It only quits the script if there is no score, i.e. a truly terrible password. As dibby is likely to be used by newbie distro builders, I do think we need to protect the end users from being hacked too easily.

**Comment by obbardc** [comment]
I am in the view of using truly terrible root passwords on embedded systems is OK, it is up to the user of the script to take our warning advice rather than flat out refuse.

**Comment by obbardc** [comment]
Awesome, happy to merge that

**Comment by danielhjames** [comment]
No problem, I've removed the `exit 1` from the script in the commit https://github.com/64studio/dibby/pull/16/commits/7c07f0ccb5c0bebb4afd0d0f9341334c3572560d

**Pull request merged**
